version: '3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  nginx:
    build: ./docker/nginx
    ports:
      - 80:80
      - 443:443
    links:
      - php
    volumes:
      - ./app:/var/www/symfony
      - ./docker/config/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/symfony.conf:/etc/nginx/sites-enabled/symfony
      - ./logs/nginx/:/var/log/nginx
  php:
    build: ./docker/php
    ports:
      - 9000:9000
    links:
      - mysql
    volumes:
      - ./app:/var/www/symfony
      - ./logs/symfony:/var/www/symfony/app/logs